###
GET http://localhost:3030/users




###
POST  http://localhost:3030/users
Content-Type: application/json

{
    "firstname":"asdasd",
    "lastname":"asdasd",
    "email":"jurayevmansurbek667@gmail.com",
    "phone":"+998996672106",
    "password":"asdasd"
}


### 